name: Sync with upstream

on:
  schedule:
    - cron: '0 0 * * *' # Ежедневно в полночь
  workflow_dispatch: # Возможность запуска вручную

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Add upstream repository
      run: |
        git remote add upstream https://github.com/HerrVonBeloff/AI-YP_24-team-42
        git fetch upstream --prune # Удаляем устаревшие ветки

    - name: Force replace main branch
      run: |
        # Переключаемся на main или создаём её
        git checkout main || git checkout -b main
        # Полностью заменяем содержимое main содержимым из upstream/main
        git reset --hard upstream/main
        # Принудительно пушим изменения в origin
        git push --force origin main

    - name: Sync other branches
      run: |
        # Перебираем все ветки, кроме main
        for branch in $(git branch -r | grep upstream/ | sed 's/upstream\///' | grep -v '^main$'); do
          echo "Processing branch: $branch"
          # Переключаемся на локальную ветку или создаём её, если её нет
          git checkout $branch || git checkout -b $branch upstream/$branch
          # Мержим изменения из upstream
          git merge upstream/$branch || echo "Merge conflict in $branch, skipping."
          # Пушим изменения в origin
          git push origin $branch || echo "Failed to push $branch"
        done
