name: Sync with upstream

on:
  schedule:
    - cron: '0 0 * * *' # Ежедневно в полночь
  workflow_dispatch: # Возможность запуска вручную

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Add upstream repository
      run: |
        git remote add upstream https://github.com/HerrVonBeloff/AI-YP_24-team-42
        git fetch upstream --prune # Удаляем устаревшие ветки
        
    - name: Merge and push all branches from upstream
      run: |
        set -e # Останавливаем выполнение при ошибке
        for branch in $(git branch -r | grep upstream/ | sed 's/upstream\///' | grep -v '^main$'); do
          echo "Processing branch: $branch"
          git checkout $branch || git checkout -b $branch upstream/$branch
          git merge upstream/$branch --allow-unrelated-histories --strategy-option theirs || echo "Merge conflict in $branch, skipping."
          git push origin $branch || echo "Failed to push $branch"
        done

    - name: Merge main branch separately
      run: |
        set -e
        git checkout main
        git merge upstream/main --allow-unrelated-histories --strategy-option theirs || echo "Merge conflict in main, skipping."
        git push origin main || echo "Failed to push main"
